name: 'dbt_sales_reporting'
version: '1.0.0'
config-version: 2

profile: 'dbt_sales_reporting'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to clean when `dbt clean` is run
  - "target"
  - "dbt_packages"

models:
  sales_reporting:
    # Config all models in this project to be materialized as tables.
    # You can override this for specific models in their own config blocks.
    +materialized: table